# Generated by Django 3.2.4 on 2022-10-09 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fname',
            field=models.CharField(default='skip', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='lname',
            field=models.CharField(default='skip', max_length=255),
            preserve_default=False,
        ),
    ]
