# Generated by Django 4.1.2 on 2022-10-17 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0003_thread_chatmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=255)),
            ],
        ),
    ]
