# Generated by Django 4.1.2 on 2022-10-17 13:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0004_newgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='newgroup',
            name='users',
            field=models.ManyToManyField(related_name='GroupUsers', to=settings.AUTH_USER_MODEL),
        ),
    ]
