# Generated by Django 4.1.2 on 2022-10-17 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0005_newgroup_users'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
