# Generated by Django 4.1.2 on 2022-10-17 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0007_newgroup_user_fk'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
