# Generated by Django 4.1.2 on 2022-10-17 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0008_alter_user_options_alter_user_table'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='thread',
            unique_together=set(),
        ),
    ]
